### ISSUE TITLE
Controlling units when exporting SVG? 

### ISSUE THREAD

**Issue by rheinason** [interopxyz/GraphicPlus#7]
Hi there! More of a feature request rather than a bug, but being able to choose what units to write the SVG in would be really great! I'm using this as an interface between Grasshopper and Inkscape to run my pen plotter and the amount of times i've drawn a tiny plot in the corner is quite high, completely my fault, but would be nice to avoid.

**Comment by interopxyz** [comment]
Great request, it has come up a few times.
Working on it now

**Comment by interopxyz** [comment]
This feature has been added in version 1.8.8.
Units are set in the Construct Drawing component
Please let me know if this configuration meets the requirements.

**Comment by rheinason** [comment]
This absolutely fits the requirements, and seems to work perfectly! A small "copy-paste error" is in the description of the input: 
![image](https://github.com/interopxyz/GraphicPlus/assets/49366360/61df2400-322b-40a4-9220-aebeec8bd451)
